/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    `maven-publish`
    id("io.freefair.lombok") version "6.5.0.2"
    id("org.springframework.boot") version "2.5.14"
}

apply(plugin = "io.spring.dependency-management")

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.spring.io/milestone")
    }

    maven {
        url = uri("https://repo.spring.io/snapshot")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    implementation("org.springframework.boot:spring-boot-starter-data-jpa")
    implementation("org.springframework.boot:spring-boot-starter-hateoas")
    implementation("org.springframework.boot:spring-boot-starter-web")
    implementation("org.springframework.boot:spring-boot-starter-validation:2.5.6")
    implementation("org.springframework.boot:spring-boot-starter-security")
    implementation("org.springframework.boot:spring-boot-starter-mail")

    implementation("org.springdoc:springdoc-openapi-ui:1.6.8")
    implementation("com.fasterxml.jackson.core:jackson-databind:2.12.6.1")
    implementation("com.flipkart.zjsonpatch:zjsonpatch:0.4.12")
    implementation("org.modelmapper:modelmapper:3.0.0")

    implementation("com.auth0:java-jwt:4.0.0-beta.0")
    runtimeOnly("org.springframework.boot:spring-boot-devtools")
    runtimeOnly("org.postgresql:postgresql:42.2.25")
    testImplementation("org.springframework.boot:spring-boot-starter-test")

}

group = "com.javadabadu"
version = "1.0.0"
description = "disney"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}